---
gitea_version: "1.12.0"
gitea_version_check: true
gitea_dl_url: "https://github.com/go-gitea/gitea/releases/download/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-{{ gitea_arch }}"

gitea_app_name: "Gitea: Git with a cup of tea"
gitea_user: "gitea"
gitea_home: "/var/lib/gitea"
gitea_shell: "/bin/bash"
gitea_systemd_cap_net_bind_service: false

gitea_repository_root: "{{ gitea_home }}/gitea-repositories"
gitea_user_repo_limit: -1

gitea_http_domain: 192.168.56.52
gitea_root_url: http://192.168.56.52:3000
gitea_protocol: http
gitea_http_listen: 127.0.0.1
gitea_http_port: 3000
gitea_disable_http_git: false
gitea_offline_mode: true

gitea_lfs_server_enabled: false
gitea_lfs_content_path: "data/lfs"

gitea_db_type: postgres
gitea_db_host: 192.168.56.53:5432
gitea_db_name: gitea
gitea_db_user: gitea
gitea_db_password: gitea
gitea_db_ssl: disable
gitea_db_path: "{{ gitea_home }}/data/gitea.db"

gitea_ssh_listen: 0.0.0.0
gitea_ssh_domain: 192.168.56.52
gitea_start_ssh: true
gitea_ssh_port: 2222

gitea_secret_key: T7hNMCPVAFqL049TkkIWxLEst3J6e1iNSzEDg1PaRNuhqI2MjW0xm0YIqCkLHs6Q
gitea_internal_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1OTIxNjYxNDl9.stq_UVNui4s-ST3p-fuh9VgpLFtW--YKpeERObwokqw

gitea_show_user_email: false
gitea_disable_gravatar: true
gitea_disable_registration: false
gitea_show_registration_button: true
gitea_require_signin: true
gitea_enable_captcha: true
gitea_only_allow_external_registration: false

gitea_force_private: false

gitea_mailer_enabled: false
gitea_mailer_skip_verify: false
gitea_mailer_tls_enabled: true
gitea_mailer_host: localhost:25
gitea_mailer_from: noreply@your.domain
gitea_mailer_user: ""
gitea_mailer_password: ""

gitea_oauth2_enabled: true
gitea_oauth2_jwt_secret: zKKvRaPnFAanabcVf0DnBWWzcryqM__j
#yMZWAoCWXqU

gitea_metrics_enabled: false
gitea_metrics_token: ~

gitea_themes: gitea,arc-green
gitea_theme_default: gitea
