---
gitea_version: "1.12.0"
gitea_version_check: true
gitea_dl_url: "https://github.com/go-gitea/gitea/releases/download/v{{ gitea_version }}/gitea-{{ gitea_version }}-linux-{{ gitea_arch }}"

gitea_app_name: "Gitea: Git with a cup of tea"
gitea_user: "gitea"
gitea_home: "/var/lib/gitea"
gitea_shell: "/bin/bash"
gitea_systemd_cap_net_bind_service: false

gitea_repository_root: "{{ gitea_home }}/gitea-repositories"
gitea_user_repo_limit: -1

gitea_http_domain: "{{ groups['webservers'][0] }}"
gitea_root_url: "{{ gitea_protocol }}://{{ gitea_http_domain }}"
gitea_protocol: https
gitea_http_listen: "{{ ansible_eth1.ipv4.address }}"
gitea_http_port: 3000
gitea_lfs_content_path: "data/lfs"

gitea_db_type: postgres
gitea_db_host: "{{ groups['dbservers'][0] }}:5432"
gitea_db_name: gitea
gitea_db_user: gitea
gitea_db_password: gitea
gitea_db_ssl: disable
gitea_db_path: "{{ gitea_home }}/data/gitea.db"

gitea_ssh_listen: 0.0.0.0
gitea_ssh_domain: 192.168.56.52
gitea_ssh_port: 2222

gitea_secret_key: T7hNMCPVAFqL049TkkIWxLEst3J6e1iNSzEDg1PaRNuhqI2MjW0xm0YIqCkLHs6Q
gitea_internal_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE1OTIxNjYxNDl9.stq_UVNui4s-ST3p-fuh9VgpLFtW--YKpeERObwokqw

gitea_mailer_host: localhost:25
gitea_mailer_from: noreply@your.domain
gitea_mailer_user: ""
gitea_mailer_password: ""

gitea_oauth2_jwt_secret: zKKvRaPnFAanabcVf0DnBWWzcryqM__jyMZWAoCWXqU

gitea_metrics_token: ~
