---
- name: nginx-reload
  systemd:
    name: nginx
    enabled: yes
    state: restarted
  when: nginx_config_status.rc == 0

- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started
