---
- name: Install Nginx Web Server on RedHat Family
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
  - nginx
  - python3-libsemanage
  when:
    ansible_os_family == "RedHat"
  notify:
    - nginx systemd
