---
- include: install.yml
- include: create_user.yml
- include: check-variables.yml
- include: firewall.yml

- name: "Check gitea version"
  shell: "set -eo pipefail; /usr/local/bin/gitea -v | cut -d' ' -f 3"
  register: gitea_active_version
  changed_when: false
  failed_when: false
  when: gitea_version_check|bool

- include: configure.yml
- include: install_systemd.yml
  when: ansible_service_mgr == "systemd"

- name: "Service gitea"
  service:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"

#- include: api_user.yml
