---
- name: Configure global settings.
  lineinfile:
    dest: "{{ pg_config_path }}/postgresql.conf"
    regexp: "^#?listen_addresses ="
    line: "listen_addresses = '*'"
    state: present
  notify: restart postgresql

- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ pg_config_path }}/pg_hba.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0600
  notify: restart postgresql

