---
- name: Create gitea user
  postgresql_user:
    name: "{{ gitea_db_user }}"
    password: "{{ gitea_db_password }}"
    encrypted: True
    state: present
  become: true
  become_user: "{{ pg_user }}"
  vars:
    ansible_ssh_pipelining: true
